version: '3.9'
services:
  redis:
    image: redis:alpine
  db:
    image: postgres:15-alpine
    volumes:
      - /Users/ojaskapre/projects/test:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  webapp:
    build: ./vote
    ports:
      - '5000:80'
    depends_on:
      - redis
  worker:
    build: ./worker
    depends_on:
      - redis
      - db
  result:
    build: ./result
    ports:
      - '5001:80'
    depends_on:
      - db
