apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-depl
  labels:
    app: webapp
    tier: frontend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: webapp
      tier: frontend
  template:
    metadata:
      name: webapp-depl-pods
      labels:
        app: webapp
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: okapre/sample-voting-webapp:m1

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 80
  selector:
    app: webapp
    tier: frontend
